# Workspace for Data Compression Tasks, Block 5
## Imports

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.fft as fft

## Workspace

## Reference

- Reference implementations are provided in this repo.
- Below is demonstration of the import structure for accessing these for relevant topics in block 3.

How to use?
- Try the task yourself, and then import the reference to compare notes.
- If you're struggling, try to formulate the problem clearly, and find the relevant line in the source.

In [12]:
from implementations import jpeg, matrix_basics, wavelet

In [15]:
jpeg.create_DCT_matrix().round(2)

array([[ 0.35,  0.35,  0.35,  0.35,  0.35,  0.35,  0.35,  0.35],
       [ 0.49,  0.42,  0.28,  0.1 , -0.1 , -0.28, -0.42, -0.49],
       [ 0.46,  0.19, -0.19, -0.46, -0.46, -0.19,  0.19,  0.46],
       [ 0.42, -0.1 , -0.49, -0.28,  0.28,  0.49,  0.1 , -0.42],
       [ 0.35, -0.35, -0.35,  0.35,  0.35, -0.35, -0.35,  0.35],
       [ 0.28, -0.49,  0.1 ,  0.42, -0.42, -0.1 ,  0.49, -0.28],
       [ 0.19, -0.46,  0.46, -0.19, -0.19,  0.46, -0.46,  0.19],
       [ 0.1 , -0.28,  0.42, -0.49,  0.49, -0.42,  0.28, -0.1 ]])

Implementation of the `h_4` components

In [16]:
wavelet.make_h4(norm=False)

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1., -1., -1.],
       [ 1., -1.,  0., -0.],
       [ 0., -0.,  1., -1.]])

Implementation of the `h_8` components

In [17]:
wavelet.make_h_8_components("a", w=1/2)

array([[ 0.5,  0.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0.5, -0.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  1. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  1. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  1. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  1. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  1. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  1. ]])